name: iotas # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1.13' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: iotas
icon: org.gnome.gitlab.cheywood.Iotas.svg
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
parts:
  iotas:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.gnome.org/cheywood/iotas.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    meson-parameters: [--prefix=/snap/iotas/current/usr]
    build-packages:
      - sqlite3
      - python3-pip
    override-pull: |
      craftctl default
      sed -e 's|Icon=@ICON@|Icon=$SNAP/usr/share/icons/hicolor/scalable/apps/org.gnome.gitlab.cheywood.Iotas.svg|' -i data/org.gnome.gitlab.cheywood.Iotas.desktop.in.in
    override-build: |
      craftctl default
      pip install --target=$CRAFT_PART_INSTALL/snap/iotas/current/usr/lib/python3/dist-packages requests
      pip install --target=$CRAFT_PART_INSTALL/snap/iotas/current/usr/lib/python3/dist-packages pygtkspellcheck
      pip install --target=$CRAFT_PART_INSTALL/snap/iotas/current/usr/lib/python3/dist-packages markdown-it-py
      pip install --target=$CRAFT_PART_INSTALL/snap/iotas/current/usr/lib/python3/dist-packages linkify-it-py
      pip install --target=$CRAFT_PART_INSTALL/snap/iotas/current/usr/lib/python3/dist-packages mdit-py-plugins
      #pip install --target=$CRAFT_PART_INSTALL/snap/iotas/current/usr/lib/python3/dist-packages PyGObject==3.42.2
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/iotas/current/usr/bin/iotas"

    organize:
      snap/iotas/current/usr: usr
    parse-info: [usr/share/metainfo/org.gnome.gitlab.cheywood.Iotas.metainfo.xml]
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - iotas
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gtk-common-themes
      - gnome-42-2204
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      rm -rf $CRAFT_PRIME/usr/lib/python3/dist-packages/PyGObject-3.44.1.dist-info
apps:
  iotas:
    command: usr/bin/iotas
    desktop: usr/share/applications/org.gnome.gitlab.cheywood.Iotas.desktop
    extensions: [gnome]
    plugs:
      - home
