name: iotas # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1.12' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: iotas
icon: org.gnome.gitlab.cheywood.Iotas.svg
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

package-repositories:
  - type: apt
    components: [main, multiverse, restricted, universe]
    suites: [kinetic, kinetic-backports, kinetic-security, kinetic-updates]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://security.ubuntu.com/ubuntu

parts:
  iotas:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.gnome.org/cheywood/iotas.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    meson-parameters: [--prefix=/snap/iotas/current/usr]
    build-packages:
      - sqlite3
      - python3-pip
    stage-packages:
      - python3-gtkspellcheck
      - python3-requests
      - python3-markdown-it
      - python3-linkify-it
      - python3-mdit-py-plugins
    override-pull: |
      craftctl default
      sed -e 's|Icon=@ICON@|Icon=$SNAP/usr/share/icons/hicolor/scalable/apps/org.gnome.gitlab.cheywood.Iotas.svg|' -i data/org.gnome.gitlab.cheywood.Iotas.desktop.in.in
    organize:
      snap/iotas/current/usr: usr
    parse-info: [usr/share/metainfo/org.gnome.gitlab.cheywood.Iotas.metainfo.xml]
    prime:
      - usr
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - iotas
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gtk-common-themes
      - gnome-42-2204
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
apps:
  iotas:
    command: usr/bin/iotas
    desktop: usr/share/applications/org.gnome.gitlab.cheywood.Iotas.desktop
    extensions: [gnome]
    plugs:
      - home
